/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivarCuentaRouteImport } from './routes/activar-cuenta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InvitacionRouteImport } from './routes/invitacion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAjustesRouteImport } from './routes/admin.ajustes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminEquipoRouteImport } from './routes/admin.equipo'
import { Route as AdminFacturacionRouteImport } from './routes/admin.facturacion'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as AdminInvitacionRouteImport } from './routes/admin.invitacion'
import { Route as EsperaTokenRouteImport } from './routes/espera.$token'
import { Route as ReservaTokenRouteImport } from './routes/reserva.$token'
import { Route as ReservarSlugRouteImport } from './routes/reservar.$slug'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin.tenants.$tenantId'
import { Route as ApiCronNotificationsRouteImport } from './routes/api.cron.notifications'
import { Route as ApiPlatformBillingReconcileRouteImport } from './routes/api.platform-billing.reconcile'
import { Route as ApiWebhooksDepositsRouteImport } from './routes/api.webhooks.deposits'
import { Route as ApiWebhooksRedsysRouteImport } from './routes/api.webhooks.redsys'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugCartaRouteImport } from './routes/t.$slug.carta'
import { Route as TSlugEquipoRouteImport } from './routes/t.$slug.equipo'
import { Route as TSlugFacturacionRouteImport } from './routes/t.$slug.facturacion'
import { Route as TSlugFacturasRouteImport } from './routes/t.$slug.facturas'
import { Route as ApiTTenantIdVerifactuCertificateRouteImport } from './routes/api.t.$tenantId.verifactu-certificate'
import { Route as TSlugLVenueRouteImport } from './routes/t.$slug.l.$venue'
import { Route as TSlugLNuevoRouteImport } from './routes/t.$slug.l.nuevo'
import { Route as TSlugSuscripcionFacturasRouteImport } from './routes/t.$slug.suscripcion.facturas'
import { Route as TSlugLVenueIndexRouteImport } from './routes/t.$slug.l.$venue.index'
import { Route as TSlugLVenueClientesRouteImport } from './routes/t.$slug.l.$venue.clientes'
import { Route as TSlugLVenueComunicacionesRouteImport } from './routes/t.$slug.l.$venue.comunicaciones'
import { Route as TSlugLVenuePlanoRouteImport } from './routes/t.$slug.l.$venue.plano'
import { Route as TSlugLVenueReservasRouteImport } from './routes/t.$slug.l.$venue.reservas'
import { Route as TSlugLVenueServicioRouteImport } from './routes/t.$slug.l.$venue.servicio'
import { Route as TSlugLVenueCuentaSessionIdRouteImport } from './routes/t.$slug.l.$venue.cuenta.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivarCuentaRoute = ActivarCuentaRouteImport.update({
  id: '/activar-cuenta',
  path: '/activar-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionRoute = InvitacionRouteImport.update({
  id: '/invitacion',
  path: '/invitacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipoRoute = AdminEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturacionRoute = AdminFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitacionRoute = AdminInvitacionRouteImport.update({
  id: '/invitacion',
  path: '/invitacion',
  getParentRoute: () => AdminRoute,
} as any)
const EsperaTokenRoute = EsperaTokenRouteImport.update({
  id: '/espera/$token',
  path: '/espera/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaTokenRoute = ReservaTokenRouteImport.update({
  id: '/reserva/$token',
  path: '/reserva/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarSlugRoute = ReservarSlugRouteImport.update({
  id: '/reservar/$slug',
  path: '/reservar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCronNotificationsRoute = ApiCronNotificationsRouteImport.update({
  id: '/api/cron/notifications',
  path: '/api/cron/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformBillingReconcileRoute =
  ApiPlatformBillingReconcileRouteImport.update({
    id: '/api/platform-billing/reconcile',
    path: '/api/platform-billing/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksDepositsRoute = ApiWebhooksDepositsRouteImport.update({
  id: '/api/webhooks/deposits',
  path: '/api/webhooks/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRedsysRoute = ApiWebhooksRedsysRouteImport.update({
  id: '/api/webhooks/redsys',
  path: '/api/webhooks/redsys',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCartaRoute = TSlugCartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugEquipoRoute = TSlugEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFacturacionRoute = TSlugFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFacturasRoute = TSlugFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => TSlugRoute,
} as any)
const ApiTTenantIdVerifactuCertificateRoute =
  ApiTTenantIdVerifactuCertificateRouteImport.update({
    id: '/api/t/$tenantId/verifactu-certificate',
    path: '/api/t/$tenantId/verifactu-certificate',
    getParentRoute: () => rootRouteImport,
  } as any)
const TSlugLVenueRoute = TSlugLVenueRouteImport.update({
  id: '/l/$venue',
  path: '/l/$venue',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugLNuevoRoute = TSlugLNuevoRouteImport.update({
  id: '/l/nuevo',
  path: '/l/nuevo',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSuscripcionFacturasRoute =
  TSlugSuscripcionFacturasRouteImport.update({
    id: '/suscripcion/facturas',
    path: '/suscripcion/facturas',
    getParentRoute: () => TSlugRoute,
  } as any)
const TSlugLVenueIndexRoute = TSlugLVenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueClientesRoute = TSlugLVenueClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueComunicacionesRoute =
  TSlugLVenueComunicacionesRouteImport.update({
    id: '/comunicaciones',
    path: '/comunicaciones',
    getParentRoute: () => TSlugLVenueRoute,
  } as any)
const TSlugLVenuePlanoRoute = TSlugLVenuePlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueReservasRoute = TSlugLVenueReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueServicioRoute = TSlugLVenueServicioRouteImport.update({
  id: '/servicio',
  path: '/servicio',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueCuentaSessionIdRoute =
  TSlugLVenueCuentaSessionIdRouteImport.update({
    id: '/cuenta/$sessionId',
    path: '/cuenta/$sessionId',
    getParentRoute: () => TSlugLVenueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activar-cuenta': typeof ActivarCuentaRoute
  '/admin': typeof AdminRouteWithChildren
  '/invitacion': typeof InvitacionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/registro': typeof RegistroRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/invitacion': typeof AdminInvitacionRoute
  '/espera/$token': typeof EsperaTokenRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/reservar/$slug': typeof ReservarSlugRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/platform-billing/reconcile': typeof ApiPlatformBillingReconcileRoute
  '/api/webhooks/deposits': typeof ApiWebhooksDepositsRoute
  '/api/webhooks/redsys': typeof ApiWebhooksRedsysRoute
  '/t/$slug/carta': typeof TSlugCartaRoute
  '/t/$slug/equipo': typeof TSlugEquipoRoute
  '/t/$slug/facturacion': typeof TSlugFacturacionRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/api/t/$tenantId/verifactu-certificate': typeof ApiTTenantIdVerifactuCertificateRoute
  '/t/$slug/l/$venue': typeof TSlugLVenueRouteWithChildren
  '/t/$slug/l/nuevo': typeof TSlugLNuevoRoute
  '/t/$slug/suscripcion/facturas': typeof TSlugSuscripcionFacturasRoute
  '/t/$slug/l/$venue/clientes': typeof TSlugLVenueClientesRoute
  '/t/$slug/l/$venue/comunicaciones': typeof TSlugLVenueComunicacionesRoute
  '/t/$slug/l/$venue/plano': typeof TSlugLVenuePlanoRoute
  '/t/$slug/l/$venue/reservas': typeof TSlugLVenueReservasRoute
  '/t/$slug/l/$venue/servicio': typeof TSlugLVenueServicioRoute
  '/t/$slug/l/$venue/': typeof TSlugLVenueIndexRoute
  '/t/$slug/l/$venue/cuenta/$sessionId': typeof TSlugLVenueCuentaSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activar-cuenta': typeof ActivarCuentaRoute
  '/invitacion': typeof InvitacionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/registro': typeof RegistroRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/invitacion': typeof AdminInvitacionRoute
  '/espera/$token': typeof EsperaTokenRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/reservar/$slug': typeof ReservarSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/platform-billing/reconcile': typeof ApiPlatformBillingReconcileRoute
  '/api/webhooks/deposits': typeof ApiWebhooksDepositsRoute
  '/api/webhooks/redsys': typeof ApiWebhooksRedsysRoute
  '/t/$slug/carta': typeof TSlugCartaRoute
  '/t/$slug/equipo': typeof TSlugEquipoRoute
  '/t/$slug/facturacion': typeof TSlugFacturacionRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/t/$slug': typeof TSlugIndexRoute
  '/api/t/$tenantId/verifactu-certificate': typeof ApiTTenantIdVerifactuCertificateRoute
  '/t/$slug/l/nuevo': typeof TSlugLNuevoRoute
  '/t/$slug/suscripcion/facturas': typeof TSlugSuscripcionFacturasRoute
  '/t/$slug/l/$venue/clientes': typeof TSlugLVenueClientesRoute
  '/t/$slug/l/$venue/comunicaciones': typeof TSlugLVenueComunicacionesRoute
  '/t/$slug/l/$venue/plano': typeof TSlugLVenuePlanoRoute
  '/t/$slug/l/$venue/reservas': typeof TSlugLVenueReservasRoute
  '/t/$slug/l/$venue/servicio': typeof TSlugLVenueServicioRoute
  '/t/$slug/l/$venue': typeof TSlugLVenueIndexRoute
  '/t/$slug/l/$venue/cuenta/$sessionId': typeof TSlugLVenueCuentaSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activar-cuenta': typeof ActivarCuentaRoute
  '/admin': typeof AdminRouteWithChildren
  '/invitacion': typeof InvitacionRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/registro': typeof RegistroRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/invitacion': typeof AdminInvitacionRoute
  '/espera/$token': typeof EsperaTokenRoute
  '/reserva/$token': typeof ReservaTokenRoute
  '/reservar/$slug': typeof ReservarSlugRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/api/platform-billing/reconcile': typeof ApiPlatformBillingReconcileRoute
  '/api/webhooks/deposits': typeof ApiWebhooksDepositsRoute
  '/api/webhooks/redsys': typeof ApiWebhooksRedsysRoute
  '/t/$slug/carta': typeof TSlugCartaRoute
  '/t/$slug/equipo': typeof TSlugEquipoRoute
  '/t/$slug/facturacion': typeof TSlugFacturacionRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/api/t/$tenantId/verifactu-certificate': typeof ApiTTenantIdVerifactuCertificateRoute
  '/t/$slug/l/$venue': typeof TSlugLVenueRouteWithChildren
  '/t/$slug/l/nuevo': typeof TSlugLNuevoRoute
  '/t/$slug/suscripcion/facturas': typeof TSlugSuscripcionFacturasRoute
  '/t/$slug/l/$venue/clientes': typeof TSlugLVenueClientesRoute
  '/t/$slug/l/$venue/comunicaciones': typeof TSlugLVenueComunicacionesRoute
  '/t/$slug/l/$venue/plano': typeof TSlugLVenuePlanoRoute
  '/t/$slug/l/$venue/reservas': typeof TSlugLVenueReservasRoute
  '/t/$slug/l/$venue/servicio': typeof TSlugLVenueServicioRoute
  '/t/$slug/l/$venue/': typeof TSlugLVenueIndexRoute
  '/t/$slug/l/$venue/cuenta/$sessionId': typeof TSlugLVenueCuentaSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activar-cuenta'
    | '/admin'
    | '/invitacion'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/admin/ajustes'
    | '/admin/auditoria'
    | '/admin/equipo'
    | '/admin/facturacion'
    | '/admin/facturas'
    | '/admin/invitacion'
    | '/espera/$token'
    | '/reserva/$token'
    | '/reservar/$slug'
    | '/t/$slug'
    | '/admin/'
    | '/admin/tenants/$tenantId'
    | '/api/cron/notifications'
    | '/api/platform-billing/reconcile'
    | '/api/webhooks/deposits'
    | '/api/webhooks/redsys'
    | '/t/$slug/carta'
    | '/t/$slug/equipo'
    | '/t/$slug/facturacion'
    | '/t/$slug/facturas'
    | '/admin/tenants/'
    | '/t/$slug/'
    | '/api/t/$tenantId/verifactu-certificate'
    | '/t/$slug/l/$venue'
    | '/t/$slug/l/nuevo'
    | '/t/$slug/suscripcion/facturas'
    | '/t/$slug/l/$venue/clientes'
    | '/t/$slug/l/$venue/comunicaciones'
    | '/t/$slug/l/$venue/plano'
    | '/t/$slug/l/$venue/reservas'
    | '/t/$slug/l/$venue/servicio'
    | '/t/$slug/l/$venue/'
    | '/t/$slug/l/$venue/cuenta/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activar-cuenta'
    | '/invitacion'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/admin/ajustes'
    | '/admin/auditoria'
    | '/admin/equipo'
    | '/admin/facturacion'
    | '/admin/facturas'
    | '/admin/invitacion'
    | '/espera/$token'
    | '/reserva/$token'
    | '/reservar/$slug'
    | '/admin'
    | '/admin/tenants/$tenantId'
    | '/api/cron/notifications'
    | '/api/platform-billing/reconcile'
    | '/api/webhooks/deposits'
    | '/api/webhooks/redsys'
    | '/t/$slug/carta'
    | '/t/$slug/equipo'
    | '/t/$slug/facturacion'
    | '/t/$slug/facturas'
    | '/admin/tenants'
    | '/t/$slug'
    | '/api/t/$tenantId/verifactu-certificate'
    | '/t/$slug/l/nuevo'
    | '/t/$slug/suscripcion/facturas'
    | '/t/$slug/l/$venue/clientes'
    | '/t/$slug/l/$venue/comunicaciones'
    | '/t/$slug/l/$venue/plano'
    | '/t/$slug/l/$venue/reservas'
    | '/t/$slug/l/$venue/servicio'
    | '/t/$slug/l/$venue'
    | '/t/$slug/l/$venue/cuenta/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/activar-cuenta'
    | '/admin'
    | '/invitacion'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/admin/ajustes'
    | '/admin/auditoria'
    | '/admin/equipo'
    | '/admin/facturacion'
    | '/admin/facturas'
    | '/admin/invitacion'
    | '/espera/$token'
    | '/reserva/$token'
    | '/reservar/$slug'
    | '/t/$slug'
    | '/admin/'
    | '/admin/tenants/$tenantId'
    | '/api/cron/notifications'
    | '/api/platform-billing/reconcile'
    | '/api/webhooks/deposits'
    | '/api/webhooks/redsys'
    | '/t/$slug/carta'
    | '/t/$slug/equipo'
    | '/t/$slug/facturacion'
    | '/t/$slug/facturas'
    | '/admin/tenants/'
    | '/t/$slug/'
    | '/api/t/$tenantId/verifactu-certificate'
    | '/t/$slug/l/$venue'
    | '/t/$slug/l/nuevo'
    | '/t/$slug/suscripcion/facturas'
    | '/t/$slug/l/$venue/clientes'
    | '/t/$slug/l/$venue/comunicaciones'
    | '/t/$slug/l/$venue/plano'
    | '/t/$slug/l/$venue/reservas'
    | '/t/$slug/l/$venue/servicio'
    | '/t/$slug/l/$venue/'
    | '/t/$slug/l/$venue/cuenta/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivarCuentaRoute: typeof ActivarCuentaRoute
  AdminRoute: typeof AdminRouteWithChildren
  InvitacionRoute: typeof InvitacionRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegistroRoute: typeof RegistroRoute
  EsperaTokenRoute: typeof EsperaTokenRoute
  ReservaTokenRoute: typeof ReservaTokenRoute
  ReservarSlugRoute: typeof ReservarSlugRoute
  TSlugRoute: typeof TSlugRouteWithChildren
  ApiCronNotificationsRoute: typeof ApiCronNotificationsRoute
  ApiPlatformBillingReconcileRoute: typeof ApiPlatformBillingReconcileRoute
  ApiWebhooksDepositsRoute: typeof ApiWebhooksDepositsRoute
  ApiWebhooksRedsysRoute: typeof ApiWebhooksRedsysRoute
  ApiTTenantIdVerifactuCertificateRoute: typeof ApiTTenantIdVerifactuCertificateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activar-cuenta': {
      id: '/activar-cuenta'
      path: '/activar-cuenta'
      fullPath: '/activar-cuenta'
      preLoaderRoute: typeof ActivarCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion': {
      id: '/invitacion'
      path: '/invitacion'
      fullPath: '/invitacion'
      preLoaderRoute: typeof InvitacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustes': {
      id: '/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipo': {
      id: '/admin/equipo'
      path: '/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AdminEquipoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion': {
      id: '/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AdminFacturacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitacion': {
      id: '/admin/invitacion'
      path: '/invitacion'
      fullPath: '/admin/invitacion'
      preLoaderRoute: typeof AdminInvitacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/espera/$token': {
      id: '/espera/$token'
      path: '/espera/$token'
      fullPath: '/espera/$token'
      preLoaderRoute: typeof EsperaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/$token': {
      id: '/reserva/$token'
      path: '/reserva/$token'
      fullPath: '/reserva/$token'
      preLoaderRoute: typeof ReservaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/$slug': {
      id: '/reservar/$slug'
      path: '/reservar/$slug'
      fullPath: '/reservar/$slug'
      preLoaderRoute: typeof ReservarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$tenantId': {
      id: '/admin/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cron/notifications': {
      id: '/api/cron/notifications'
      path: '/api/cron/notifications'
      fullPath: '/api/cron/notifications'
      preLoaderRoute: typeof ApiCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform-billing/reconcile': {
      id: '/api/platform-billing/reconcile'
      path: '/api/platform-billing/reconcile'
      fullPath: '/api/platform-billing/reconcile'
      preLoaderRoute: typeof ApiPlatformBillingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/deposits': {
      id: '/api/webhooks/deposits'
      path: '/api/webhooks/deposits'
      fullPath: '/api/webhooks/deposits'
      preLoaderRoute: typeof ApiWebhooksDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/redsys': {
      id: '/api/webhooks/redsys'
      path: '/api/webhooks/redsys'
      fullPath: '/api/webhooks/redsys'
      preLoaderRoute: typeof ApiWebhooksRedsysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/carta': {
      id: '/t/$slug/carta'
      path: '/carta'
      fullPath: '/t/$slug/carta'
      preLoaderRoute: typeof TSlugCartaRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/equipo': {
      id: '/t/$slug/equipo'
      path: '/equipo'
      fullPath: '/t/$slug/equipo'
      preLoaderRoute: typeof TSlugEquipoRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/facturacion': {
      id: '/t/$slug/facturacion'
      path: '/facturacion'
      fullPath: '/t/$slug/facturacion'
      preLoaderRoute: typeof TSlugFacturacionRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/facturas': {
      id: '/t/$slug/facturas'
      path: '/facturas'
      fullPath: '/t/$slug/facturas'
      preLoaderRoute: typeof TSlugFacturasRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/api/t/$tenantId/verifactu-certificate': {
      id: '/api/t/$tenantId/verifactu-certificate'
      path: '/api/t/$tenantId/verifactu-certificate'
      fullPath: '/api/t/$tenantId/verifactu-certificate'
      preLoaderRoute: typeof ApiTTenantIdVerifactuCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/l/$venue': {
      id: '/t/$slug/l/$venue'
      path: '/l/$venue'
      fullPath: '/t/$slug/l/$venue'
      preLoaderRoute: typeof TSlugLVenueRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/l/nuevo': {
      id: '/t/$slug/l/nuevo'
      path: '/l/nuevo'
      fullPath: '/t/$slug/l/nuevo'
      preLoaderRoute: typeof TSlugLNuevoRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/suscripcion/facturas': {
      id: '/t/$slug/suscripcion/facturas'
      path: '/suscripcion/facturas'
      fullPath: '/t/$slug/suscripcion/facturas'
      preLoaderRoute: typeof TSlugSuscripcionFacturasRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/l/$venue/': {
      id: '/t/$slug/l/$venue/'
      path: '/'
      fullPath: '/t/$slug/l/$venue/'
      preLoaderRoute: typeof TSlugLVenueIndexRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/clientes': {
      id: '/t/$slug/l/$venue/clientes'
      path: '/clientes'
      fullPath: '/t/$slug/l/$venue/clientes'
      preLoaderRoute: typeof TSlugLVenueClientesRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/comunicaciones': {
      id: '/t/$slug/l/$venue/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/t/$slug/l/$venue/comunicaciones'
      preLoaderRoute: typeof TSlugLVenueComunicacionesRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/plano': {
      id: '/t/$slug/l/$venue/plano'
      path: '/plano'
      fullPath: '/t/$slug/l/$venue/plano'
      preLoaderRoute: typeof TSlugLVenuePlanoRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/reservas': {
      id: '/t/$slug/l/$venue/reservas'
      path: '/reservas'
      fullPath: '/t/$slug/l/$venue/reservas'
      preLoaderRoute: typeof TSlugLVenueReservasRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/servicio': {
      id: '/t/$slug/l/$venue/servicio'
      path: '/servicio'
      fullPath: '/t/$slug/l/$venue/servicio'
      preLoaderRoute: typeof TSlugLVenueServicioRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/cuenta/$sessionId': {
      id: '/t/$slug/l/$venue/cuenta/$sessionId'
      path: '/cuenta/$sessionId'
      fullPath: '/t/$slug/l/$venue/cuenta/$sessionId'
      preLoaderRoute: typeof TSlugLVenueCuentaSessionIdRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminEquipoRoute: typeof AdminEquipoRoute
  AdminFacturacionRoute: typeof AdminFacturacionRoute
  AdminFacturasRoute: typeof AdminFacturasRoute
  AdminInvitacionRoute: typeof AdminInvitacionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAjustesRoute: AdminAjustesRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminEquipoRoute: AdminEquipoRoute,
  AdminFacturacionRoute: AdminFacturacionRoute,
  AdminFacturasRoute: AdminFacturasRoute,
  AdminInvitacionRoute: AdminInvitacionRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TSlugLVenueRouteChildren {
  TSlugLVenueClientesRoute: typeof TSlugLVenueClientesRoute
  TSlugLVenueComunicacionesRoute: typeof TSlugLVenueComunicacionesRoute
  TSlugLVenuePlanoRoute: typeof TSlugLVenuePlanoRoute
  TSlugLVenueReservasRoute: typeof TSlugLVenueReservasRoute
  TSlugLVenueServicioRoute: typeof TSlugLVenueServicioRoute
  TSlugLVenueIndexRoute: typeof TSlugLVenueIndexRoute
  TSlugLVenueCuentaSessionIdRoute: typeof TSlugLVenueCuentaSessionIdRoute
}

const TSlugLVenueRouteChildren: TSlugLVenueRouteChildren = {
  TSlugLVenueClientesRoute: TSlugLVenueClientesRoute,
  TSlugLVenueComunicacionesRoute: TSlugLVenueComunicacionesRoute,
  TSlugLVenuePlanoRoute: TSlugLVenuePlanoRoute,
  TSlugLVenueReservasRoute: TSlugLVenueReservasRoute,
  TSlugLVenueServicioRoute: TSlugLVenueServicioRoute,
  TSlugLVenueIndexRoute: TSlugLVenueIndexRoute,
  TSlugLVenueCuentaSessionIdRoute: TSlugLVenueCuentaSessionIdRoute,
}

const TSlugLVenueRouteWithChildren = TSlugLVenueRoute._addFileChildren(
  TSlugLVenueRouteChildren,
)

interface TSlugRouteChildren {
  TSlugCartaRoute: typeof TSlugCartaRoute
  TSlugEquipoRoute: typeof TSlugEquipoRoute
  TSlugFacturacionRoute: typeof TSlugFacturacionRoute
  TSlugFacturasRoute: typeof TSlugFacturasRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
  TSlugLVenueRoute: typeof TSlugLVenueRouteWithChildren
  TSlugLNuevoRoute: typeof TSlugLNuevoRoute
  TSlugSuscripcionFacturasRoute: typeof TSlugSuscripcionFacturasRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugCartaRoute: TSlugCartaRoute,
  TSlugEquipoRoute: TSlugEquipoRoute,
  TSlugFacturacionRoute: TSlugFacturacionRoute,
  TSlugFacturasRoute: TSlugFacturasRoute,
  TSlugIndexRoute: TSlugIndexRoute,
  TSlugLVenueRoute: TSlugLVenueRouteWithChildren,
  TSlugLNuevoRoute: TSlugLNuevoRoute,
  TSlugSuscripcionFacturasRoute: TSlugSuscripcionFacturasRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivarCuentaRoute: ActivarCuentaRoute,
  AdminRoute: AdminRouteWithChildren,
  InvitacionRoute: InvitacionRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegistroRoute: RegistroRoute,
  EsperaTokenRoute: EsperaTokenRoute,
  ReservaTokenRoute: ReservaTokenRoute,
  ReservarSlugRoute: ReservarSlugRoute,
  TSlugRoute: TSlugRouteWithChildren,
  ApiCronNotificationsRoute: ApiCronNotificationsRoute,
  ApiPlatformBillingReconcileRoute: ApiPlatformBillingReconcileRoute,
  ApiWebhooksDepositsRoute: ApiWebhooksDepositsRoute,
  ApiWebhooksRedsysRoute: ApiWebhooksRedsysRoute,
  ApiTTenantIdVerifactuCertificateRoute: ApiTTenantIdVerifactuCertificateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
