/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as ApiPlatformBillingReconcileRouteImport } from './routes/api.platform-billing.reconcile'
import { Route as ApiWebhooksRedsysRouteImport } from './routes/api.webhooks.redsys'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugCartaRouteImport } from './routes/t.$slug.carta'
import { Route as TSlugFacturacionRouteImport } from './routes/t.$slug.facturacion'
import { Route as TSlugFacturasRouteImport } from './routes/t.$slug.facturas'
import { Route as TSlugLVenueRouteImport } from './routes/t.$slug.l.$venue'
import { Route as TSlugLNuevoRouteImport } from './routes/t.$slug.l.nuevo'
import { Route as TSlugSuscripcionFacturasRouteImport } from './routes/t.$slug.suscripcion.facturas'
import { Route as TSlugLVenueIndexRouteImport } from './routes/t.$slug.l.$venue.index'
import { Route as TSlugLVenuePlanoRouteImport } from './routes/t.$slug.l.$venue.plano'
import { Route as TSlugLVenueReservasRouteImport } from './routes/t.$slug.l.$venue.reservas'
import { Route as TSlugLVenueServicioRouteImport } from './routes/t.$slug.l.$venue.servicio'
import { Route as TSlugLVenueCuentaSessionIdRouteImport } from './routes/t.$slug.l.$venue.cuenta.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/admin/facturas',
  path: '/admin/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformBillingReconcileRoute =
  ApiPlatformBillingReconcileRouteImport.update({
    id: '/api/platform-billing/reconcile',
    path: '/api/platform-billing/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksRedsysRoute = ApiWebhooksRedsysRouteImport.update({
  id: '/api/webhooks/redsys',
  path: '/api/webhooks/redsys',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCartaRoute = TSlugCartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFacturacionRoute = TSlugFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFacturasRoute = TSlugFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugLVenueRoute = TSlugLVenueRouteImport.update({
  id: '/l/$venue',
  path: '/l/$venue',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugLNuevoRoute = TSlugLNuevoRouteImport.update({
  id: '/l/nuevo',
  path: '/l/nuevo',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSuscripcionFacturasRoute =
  TSlugSuscripcionFacturasRouteImport.update({
    id: '/suscripcion/facturas',
    path: '/suscripcion/facturas',
    getParentRoute: () => TSlugRoute,
  } as any)
const TSlugLVenueIndexRoute = TSlugLVenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenuePlanoRoute = TSlugLVenuePlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueReservasRoute = TSlugLVenueReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueServicioRoute = TSlugLVenueServicioRouteImport.update({
  id: '/servicio',
  path: '/servicio',
  getParentRoute: () => TSlugLVenueRoute,
} as any)
const TSlugLVenueCuentaSessionIdRoute =
  TSlugLVenueCuentaSessionIdRouteImport.update({
    id: '/cuenta/$sessionId',
    path: '/cuenta/$sessionId',
    getParentRoute: () => TSlugLVenueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/platform-billing/reconcile': typeof ApiPlatformBillingReconcileRoute
  '/api/webhooks/redsys': typeof ApiWebhooksRedsysRoute
  '/t/$slug/carta': typeof TSlugCartaRoute
  '/t/$slug/facturacion': typeof TSlugFacturacionRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/l/$venue': typeof TSlugLVenueRouteWithChildren
  '/t/$slug/l/nuevo': typeof TSlugLNuevoRoute
  '/t/$slug/suscripcion/facturas': typeof TSlugSuscripcionFacturasRoute
  '/t/$slug/l/$venue/plano': typeof TSlugLVenuePlanoRoute
  '/t/$slug/l/$venue/reservas': typeof TSlugLVenueReservasRoute
  '/t/$slug/l/$venue/servicio': typeof TSlugLVenueServicioRoute
  '/t/$slug/l/$venue/': typeof TSlugLVenueIndexRoute
  '/t/$slug/l/$venue/cuenta/$sessionId': typeof TSlugLVenueCuentaSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin': typeof AdminIndexRoute
  '/api/platform-billing/reconcile': typeof ApiPlatformBillingReconcileRoute
  '/api/webhooks/redsys': typeof ApiWebhooksRedsysRoute
  '/t/$slug/carta': typeof TSlugCartaRoute
  '/t/$slug/facturacion': typeof TSlugFacturacionRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/t/$slug': typeof TSlugIndexRoute
  '/t/$slug/l/nuevo': typeof TSlugLNuevoRoute
  '/t/$slug/suscripcion/facturas': typeof TSlugSuscripcionFacturasRoute
  '/t/$slug/l/$venue/plano': typeof TSlugLVenuePlanoRoute
  '/t/$slug/l/$venue/reservas': typeof TSlugLVenueReservasRoute
  '/t/$slug/l/$venue/servicio': typeof TSlugLVenueServicioRoute
  '/t/$slug/l/$venue': typeof TSlugLVenueIndexRoute
  '/t/$slug/l/$venue/cuenta/$sessionId': typeof TSlugLVenueCuentaSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/platform-billing/reconcile': typeof ApiPlatformBillingReconcileRoute
  '/api/webhooks/redsys': typeof ApiWebhooksRedsysRoute
  '/t/$slug/carta': typeof TSlugCartaRoute
  '/t/$slug/facturacion': typeof TSlugFacturacionRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/l/$venue': typeof TSlugLVenueRouteWithChildren
  '/t/$slug/l/nuevo': typeof TSlugLNuevoRoute
  '/t/$slug/suscripcion/facturas': typeof TSlugSuscripcionFacturasRoute
  '/t/$slug/l/$venue/plano': typeof TSlugLVenuePlanoRoute
  '/t/$slug/l/$venue/reservas': typeof TSlugLVenueReservasRoute
  '/t/$slug/l/$venue/servicio': typeof TSlugLVenueServicioRoute
  '/t/$slug/l/$venue/': typeof TSlugLVenueIndexRoute
  '/t/$slug/l/$venue/cuenta/$sessionId': typeof TSlugLVenueCuentaSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin/facturas'
    | '/t/$slug'
    | '/admin/'
    | '/api/platform-billing/reconcile'
    | '/api/webhooks/redsys'
    | '/t/$slug/carta'
    | '/t/$slug/facturacion'
    | '/t/$slug/facturas'
    | '/t/$slug/'
    | '/t/$slug/l/$venue'
    | '/t/$slug/l/nuevo'
    | '/t/$slug/suscripcion/facturas'
    | '/t/$slug/l/$venue/plano'
    | '/t/$slug/l/$venue/reservas'
    | '/t/$slug/l/$venue/servicio'
    | '/t/$slug/l/$venue/'
    | '/t/$slug/l/$venue/cuenta/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin/facturas'
    | '/admin'
    | '/api/platform-billing/reconcile'
    | '/api/webhooks/redsys'
    | '/t/$slug/carta'
    | '/t/$slug/facturacion'
    | '/t/$slug/facturas'
    | '/t/$slug'
    | '/t/$slug/l/nuevo'
    | '/t/$slug/suscripcion/facturas'
    | '/t/$slug/l/$venue/plano'
    | '/t/$slug/l/$venue/reservas'
    | '/t/$slug/l/$venue/servicio'
    | '/t/$slug/l/$venue'
    | '/t/$slug/l/$venue/cuenta/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin/facturas'
    | '/t/$slug'
    | '/admin/'
    | '/api/platform-billing/reconcile'
    | '/api/webhooks/redsys'
    | '/t/$slug/carta'
    | '/t/$slug/facturacion'
    | '/t/$slug/facturas'
    | '/t/$slug/'
    | '/t/$slug/l/$venue'
    | '/t/$slug/l/nuevo'
    | '/t/$slug/suscripcion/facturas'
    | '/t/$slug/l/$venue/plano'
    | '/t/$slug/l/$venue/reservas'
    | '/t/$slug/l/$venue/servicio'
    | '/t/$slug/l/$venue/'
    | '/t/$slug/l/$venue/cuenta/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AdminFacturasRoute: typeof AdminFacturasRoute
  TSlugRoute: typeof TSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPlatformBillingReconcileRoute: typeof ApiPlatformBillingReconcileRoute
  ApiWebhooksRedsysRoute: typeof ApiWebhooksRedsysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/admin/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform-billing/reconcile': {
      id: '/api/platform-billing/reconcile'
      path: '/api/platform-billing/reconcile'
      fullPath: '/api/platform-billing/reconcile'
      preLoaderRoute: typeof ApiPlatformBillingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/redsys': {
      id: '/api/webhooks/redsys'
      path: '/api/webhooks/redsys'
      fullPath: '/api/webhooks/redsys'
      preLoaderRoute: typeof ApiWebhooksRedsysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/carta': {
      id: '/t/$slug/carta'
      path: '/carta'
      fullPath: '/t/$slug/carta'
      preLoaderRoute: typeof TSlugCartaRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/facturacion': {
      id: '/t/$slug/facturacion'
      path: '/facturacion'
      fullPath: '/t/$slug/facturacion'
      preLoaderRoute: typeof TSlugFacturacionRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/facturas': {
      id: '/t/$slug/facturas'
      path: '/facturas'
      fullPath: '/t/$slug/facturas'
      preLoaderRoute: typeof TSlugFacturasRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/l/$venue': {
      id: '/t/$slug/l/$venue'
      path: '/l/$venue'
      fullPath: '/t/$slug/l/$venue'
      preLoaderRoute: typeof TSlugLVenueRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/l/nuevo': {
      id: '/t/$slug/l/nuevo'
      path: '/l/nuevo'
      fullPath: '/t/$slug/l/nuevo'
      preLoaderRoute: typeof TSlugLNuevoRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/suscripcion/facturas': {
      id: '/t/$slug/suscripcion/facturas'
      path: '/suscripcion/facturas'
      fullPath: '/t/$slug/suscripcion/facturas'
      preLoaderRoute: typeof TSlugSuscripcionFacturasRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/l/$venue/': {
      id: '/t/$slug/l/$venue/'
      path: '/'
      fullPath: '/t/$slug/l/$venue/'
      preLoaderRoute: typeof TSlugLVenueIndexRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/plano': {
      id: '/t/$slug/l/$venue/plano'
      path: '/plano'
      fullPath: '/t/$slug/l/$venue/plano'
      preLoaderRoute: typeof TSlugLVenuePlanoRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/reservas': {
      id: '/t/$slug/l/$venue/reservas'
      path: '/reservas'
      fullPath: '/t/$slug/l/$venue/reservas'
      preLoaderRoute: typeof TSlugLVenueReservasRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/servicio': {
      id: '/t/$slug/l/$venue/servicio'
      path: '/servicio'
      fullPath: '/t/$slug/l/$venue/servicio'
      preLoaderRoute: typeof TSlugLVenueServicioRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
    '/t/$slug/l/$venue/cuenta/$sessionId': {
      id: '/t/$slug/l/$venue/cuenta/$sessionId'
      path: '/cuenta/$sessionId'
      fullPath: '/t/$slug/l/$venue/cuenta/$sessionId'
      preLoaderRoute: typeof TSlugLVenueCuentaSessionIdRouteImport
      parentRoute: typeof TSlugLVenueRoute
    }
  }
}

interface TSlugLVenueRouteChildren {
  TSlugLVenuePlanoRoute: typeof TSlugLVenuePlanoRoute
  TSlugLVenueReservasRoute: typeof TSlugLVenueReservasRoute
  TSlugLVenueServicioRoute: typeof TSlugLVenueServicioRoute
  TSlugLVenueIndexRoute: typeof TSlugLVenueIndexRoute
  TSlugLVenueCuentaSessionIdRoute: typeof TSlugLVenueCuentaSessionIdRoute
}

const TSlugLVenueRouteChildren: TSlugLVenueRouteChildren = {
  TSlugLVenuePlanoRoute: TSlugLVenuePlanoRoute,
  TSlugLVenueReservasRoute: TSlugLVenueReservasRoute,
  TSlugLVenueServicioRoute: TSlugLVenueServicioRoute,
  TSlugLVenueIndexRoute: TSlugLVenueIndexRoute,
  TSlugLVenueCuentaSessionIdRoute: TSlugLVenueCuentaSessionIdRoute,
}

const TSlugLVenueRouteWithChildren = TSlugLVenueRoute._addFileChildren(
  TSlugLVenueRouteChildren,
)

interface TSlugRouteChildren {
  TSlugCartaRoute: typeof TSlugCartaRoute
  TSlugFacturacionRoute: typeof TSlugFacturacionRoute
  TSlugFacturasRoute: typeof TSlugFacturasRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
  TSlugLVenueRoute: typeof TSlugLVenueRouteWithChildren
  TSlugLNuevoRoute: typeof TSlugLNuevoRoute
  TSlugSuscripcionFacturasRoute: typeof TSlugSuscripcionFacturasRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugCartaRoute: TSlugCartaRoute,
  TSlugFacturacionRoute: TSlugFacturacionRoute,
  TSlugFacturasRoute: TSlugFacturasRoute,
  TSlugIndexRoute: TSlugIndexRoute,
  TSlugLVenueRoute: TSlugLVenueRouteWithChildren,
  TSlugLNuevoRoute: TSlugLNuevoRoute,
  TSlugSuscripcionFacturasRoute: TSlugSuscripcionFacturasRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AdminFacturasRoute: AdminFacturasRoute,
  TSlugRoute: TSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiPlatformBillingReconcileRoute: ApiPlatformBillingReconcileRoute,
  ApiWebhooksRedsysRoute: ApiWebhooksRedsysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
