/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugFacturasRouteImport } from './routes/t.$slug.facturas'
import { Route as TSlugPlanoRouteImport } from './routes/t.$slug.plano'
import { Route as TSlugReservasRouteImport } from './routes/t.$slug.reservas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFacturasRoute = TSlugFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPlanoRoute = TSlugPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugReservasRoute = TSlugReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => TSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/t/$slug/plano': typeof TSlugPlanoRoute
  '/t/$slug/reservas': typeof TSlugReservasRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/t/$slug/plano': typeof TSlugPlanoRoute
  '/t/$slug/reservas': typeof TSlugReservasRoute
  '/t/$slug': typeof TSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/t/$slug/facturas': typeof TSlugFacturasRoute
  '/t/$slug/plano': typeof TSlugPlanoRoute
  '/t/$slug/reservas': typeof TSlugReservasRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/t/$slug'
    | '/admin/'
    | '/t/$slug/facturas'
    | '/t/$slug/plano'
    | '/t/$slug/reservas'
    | '/t/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/t/$slug/facturas'
    | '/t/$slug/plano'
    | '/t/$slug/reservas'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/t/$slug'
    | '/admin/'
    | '/t/$slug/facturas'
    | '/t/$slug/plano'
    | '/t/$slug/reservas'
    | '/t/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TSlugRoute: typeof TSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/facturas': {
      id: '/t/$slug/facturas'
      path: '/facturas'
      fullPath: '/t/$slug/facturas'
      preLoaderRoute: typeof TSlugFacturasRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/plano': {
      id: '/t/$slug/plano'
      path: '/plano'
      fullPath: '/t/$slug/plano'
      preLoaderRoute: typeof TSlugPlanoRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/reservas': {
      id: '/t/$slug/reservas'
      path: '/reservas'
      fullPath: '/t/$slug/reservas'
      preLoaderRoute: typeof TSlugReservasRouteImport
      parentRoute: typeof TSlugRoute
    }
  }
}

interface TSlugRouteChildren {
  TSlugFacturasRoute: typeof TSlugFacturasRoute
  TSlugPlanoRoute: typeof TSlugPlanoRoute
  TSlugReservasRoute: typeof TSlugReservasRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugFacturasRoute: TSlugFacturasRoute,
  TSlugPlanoRoute: TSlugPlanoRoute,
  TSlugReservasRoute: TSlugReservasRoute,
  TSlugIndexRoute: TSlugIndexRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TSlugRoute: TSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
