create table if not exists public.gift_cards (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, code text not null, initial_balance_cents integer not null check (initial_balance_cents > 0), balance_cents integer not null check (balance_cents >= 0), status text not null default 'active' check (status in ('active','exhausted','cancelled')), created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tenant_id, code));
create table if not exists public.gift_card_transactions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, gift_card_id uuid not null references public.gift_cards(id) on delete cascade, amount_cents integer not null check (amount_cents <> 0), reason text not null, created_by uuid references auth.users(id), created_at timestamptz not null default now());
alter table public.gift_cards enable row level security; alter table public.gift_card_transactions enable row level security;
create policy gift_cards_read on public.gift_cards for select to authenticated using (public.has_tenant_role(tenant_id, array['owner','manager','waiter','accountant']::public.tenant_role[]));
create policy gift_cards_write on public.gift_cards for all to authenticated using (public.has_tenant_role(tenant_id, array['owner','manager']::public.tenant_role[])) with check (public.has_tenant_role(tenant_id, array['owner','manager']::public.tenant_role[]));
create policy gift_card_transactions_read on public.gift_card_transactions for select to authenticated using (public.has_tenant_role(tenant_id, array['owner','manager','accountant']::public.tenant_role[]));
create policy gift_card_transactions_insert on public.gift_card_transactions for insert to authenticated with check (public.has_tenant_role(tenant_id, array['owner','manager','waiter']::public.tenant_role[]));
create or replace function public.redeem_gift_card(p_tenant_id uuid, p_code text, p_amount_cents integer) returns void language plpgsql security invoker set search_path=public as $$ declare v_card gift_cards; begin if not public.has_tenant_role(p_tenant_id, array['owner','manager','waiter']::public.tenant_role[]) then raise exception 'forbidden'; end if; if p_amount_cents <= 0 then raise exception 'invalid_gift_card_amount'; end if; select * into v_card from gift_cards where tenant_id=p_tenant_id and code=upper(regexp_replace(trim(p_code), '\s+', '', 'g')) and status='active' for update; if not found or v_card.balance_cents < p_amount_cents then raise exception 'gift_card_insufficient_balance'; end if; update gift_cards set balance_cents=balance_cents-p_amount_cents, status=case when balance_cents-p_amount_cents=0 then 'exhausted' else 'active' end, updated_at=now() where id=v_card.id; insert into gift_card_transactions(tenant_id,gift_card_id,amount_cents,reason,created_by) values(p_tenant_id,v_card.id,-p_amount_cents,'Canje de tarjeta regalo',auth.uid()); end; $$;
revoke all on function public.redeem_gift_card(uuid,text,integer) from public; grant execute on function public.redeem_gift_card(uuid,text,integer) to authenticated;
